services:
  # Frontend - Static Site
  - type: web
    name: collegeadmitted-frontend
    env: static
    buildCommand: cd frontend && npm install && npm run build
    staticPublishPath: ./frontend/.next
    branch: main
    routes:
      - type: rewrite
        source: /*
        destination: /index.html
    envVars:
      - key: NODE_ENV
        value: production

  # Backend - Web Service
  - type: web
    name: collegeadmitted-backend
    env: python
    buildCommand: cd backend && pip install -r requirements.txt
    startCommand: cd backend && uvicorn app.main:app --host 0.0.0.0 --port $PORT
    branch: main
    envVars:
      - key: ENVIRONMENT
        value: production
      - key: POSTGRES_USER
        sync: false
      - key: POSTGRES_PASSWORD
        sync: false
      - key: POSTGRES_DB
        sync: false
      - key: SECRET_KEY
        sync: false
      - key: MISTRAL_API_KEY
        sync: false
      - key: DATABASE_URL
        fromDatabase:
          name: collegeadmitted-db
          property: connectionString

databases:
  - name: collegeadmitted-db
    databaseName: collegeadmitted
    user: collegeadmitted
    plan: standard 