# Exported from Render on 2025-03-14T21:09:44Z
services:
- type: web
  name: collegeadmitted_dev
  runtime: static
  repo: https://github.com/huntersinclair/collegeadmitted
  branch: develop
  buildCommand: npm run build
  staticPublishPath: out
  rootDir: frontend
## backend
- type: web
  name: collegeadmitted_dev_be
  runtime: docker
  repo: https://github.com/huntersinclair/collegeadmitted
  branch: develop
  plan: free
  envVars:
  - key: JWT_SECRET
    sync: false
  - key: SUPABASE_KEY
    sync: false
  - key: SUPABASE_URL
    sync: false
  - key: SECRET_KEY
    sync: false
  - key: FACEBOOK_CLIENT_SECRET
    sync: false
  - key: FACEBOOK_CLIENT_ID
    sync: false
  - key: GOOGLE_CLIENT_SECRET
    sync: false
  - key: GOOGLE_CLIENT_ID
    sync: false
  - key: BACKEND_URL
    sync: false
  - key: FRONTEND_URL
    sync: false
  - key: ACCESS_TOKEN_EXPIRE_MINUTES
    sync: false
  - key: SUPABASE_ACCESS_TOKEN
    sync: false
  - key: SUPABASE_PROJECT_ID
    sync: false
  region: oregon
  dockerContext: .
  dockerfilePath: ./Dockerfile
  rootDir: backend
version: "1"

