name: Continuous Integration

on:
  push:
    branches: [ develop, uat, main ]
  pull_request:
    branches: [ develop, uat, main ]

jobs:
  test-backend:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'
        
    - name: Install dependencies
      run: |
        cd backend
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install pytest-cov
        
    - name: Run tests
      env:
        SUPABASE_URL: ${{ secrets.SUPABASE_URL }}
        SUPABASE_KEY: ${{ secrets.SUPABASE_KEY }}
        JWT_SECRET: ${{ secrets.JWT_SECRET }}
        SECRET_KEY: test_secret_key
      run: |
        cd backend
        pytest --cov=app --cov-report=xml
        
    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v3
      with:
        file: ./backend/coverage.xml

  test-frontend:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'
        
    - name: Install dependencies
      run: |
        cd frontend
        npm ci
        
    - name: Run tests
      run: |
        cd frontend
        npm test
        
    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v3
      with:
        file: ./frontend/coverage/coverage-final.json
      continue-on-error: true 
      
  run-migrations:
    runs-on: ubuntu-latest
    needs: [test-backend, test-frontend]
    if: github.event_name == 'push' && (github.ref == 'refs/heads/develop' || github.ref == 'refs/heads/uat' || github.ref == 'refs/heads/main')
    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0
        
    - name: Check for migration changes
      id: check_migrations
      run: |
        if [ -n "$(git diff --name-only ${{ github.event.before }} ${{ github.event.after }} | grep -E 'supabase/migrations/')" ]; then
          echo "migrations_changed=true" >> $GITHUB_OUTPUT
        else
          echo "migrations_changed=false" >> $GITHUB_OUTPUT
        fi
        
    - name: Set up Node.js
      if: steps.check_migrations.outputs.migrations_changed == 'true'
      uses: actions/setup-node@v3
      with:
        node-version: '20'
        
    - name: Install Supabase CLI
      if: steps.check_migrations.outputs.migrations_changed == 'true'
      run: npm install -g supabase
      
    - name: Deploy migrations to Supabase
      if: steps.check_migrations.outputs.migrations_changed == 'true'
      env:
        SUPABASE_ACCESS_TOKEN: ${{ secrets.SUPABASE_ACCESS_TOKEN }}
        SUPABASE_PROJECT_ID: ${{ secrets.SUPABASE_PROJECT_ID }}
      run: |
        supabase link --project-ref $SUPABASE_PROJECT_ID
        supabase db push 