name: Deploy Supabase Migrations

on:
  push:
    branches:
      - develop
      - uat
      - main
    paths:
      - 'supabase/migrations/**'
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    env:
      SUPABASE_ACCESS_TOKEN: ${{ secrets.SUPABASE_ACCESS_TOKEN }}
      SUPABASE_PROJECT_ID: ${{ secrets.SUPABASE_PROJECT_ID }}
      
    steps:
      - uses: actions/checkout@v4
      
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          
      - name: Install Supabase CLI
        run: npm install -g supabase
      
      - name: Deploy migrations to Supabase
        run: |
          supabase link --project-ref $SUPABASE_PROJECT_ID
          supabase db push
          
      - name: Trigger Render Deploy
        if: success()
        run: |
          # Only trigger Render deploy if migrations were actually applied
          if [ "${{ github.event_name }}" == "push" ] && [ -n "$(git diff --name-only ${{ github.event.before }} ${{ github.event.after }} | grep -E 'supabase/migrations/')" ]; then
            curl -X POST "${{ secrets.RENDER_DEPLOY_HOOK_URL }}"
            echo "Triggered Render deployment after successful DB migration"
          else
            echo "No migration changes detected, skipping Render deployment trigger"
          fi 